services:
  db:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
